public/index.html, src/sass/layout/_main.scss, src/sass/layout/_sites.scss, src/sass/layout/layout.scss, src/sass/site/_colors.scss, src/sass/site/_text.scss
Related to #5 and #2. Also update website baseline and some styles.
=> Add cssdb and Is Houdini Ready Yet?

public/index.html, src/sass/site/_colors.scss
=> Add more websites and categorize them

public/index.html, src/sass/layout/_sites.scss, src/sass/site/_colors.scss, src/sass/site/_ctn.scss, src/sass/site/_links.scss, src/sass/site/_text.scss
=> Fix layout degradation on small screens

package-lock.json, src/sass/site/_ctn.scss
=> Fix Chromium visual hover glitch

public/index.html, src/sass/site/_colors.scss
=> Add Web Platform Tests Dashboard

.env.example, README.md, package-lock.json, package.json, playwright.config.mjs, tests/index.spec.mjs, tests/links.spec.mjs
A very simple start with [Playwright](https://playwright.dev). Next step should be to run a GitHub action on PR.
=> Add some tests using Playwright

tests/links.spec.mjs, tests/utils/urls.mjs
This makes sure all `<a href="https://some-website">` have a valid URL.
=> Test links validity

src/index.html, src/sass/site/_colors.scss
=> Add Privacy Tests

package-lock.json, package.json, src/index.html, vite.config.js
Also:
- makes `.env` optional;
- fixes a misplaced space after Yvonne Schüttler name.
=> Update Vite from 3 to 4

.github/workflows/links-cron.yml
The first run should happen on Monday morning.
=> Check links periodically

.env.example, .eslintrc.json, package-lock.json, package.json, tests/accessibility-axe.spec.mjs, tests/links.spec.mjs, tests/title.spec.mjs, tests/utils/url.mjs, vite.config.js
Yes, it’s just for the tests. 🙃
=> Add ESLint configuration

tests/accessibility-axe.spec.mjs, tests/utils/axe-core.mjs
=> Exclude tracking image from accessibility tests

package-lock.json, playwright.config.mjs, src/index.html, src/sass/_base.scss, src/sass/layout/_main.scss, tests/links.spec.mjs, tests/utils/url.mjs
=> Add anchor links

.github/workflows/size-limit.yml, package-lock.json, package.json
Goal: use [`size-limit`](https://github.com/ai/size-limit/) and its [GitHub action](https://github.com/andresz1/size-limit-action), and hopefully show a size report by type of assets (to be defined).
=> Add `size-limit`

src/index.html, src/sass/site/_colors.scss
=> Add Mozilla and WebKit standards positions

src/index.html
=> Remove forgtten Twitter card meta

package-lock.json, vite.config.js
=> Fix footer items spacings

.env.example
It validates Herd path and make it the default one.
=> Update local certificates in `.env.example`

src/css/media-queries/resolution.css
This code isn’t used in the website, but still worth fixing it.
=> Fix condition for multiple media queries

src/css/components/site/ctn.css, src/css/components/site/links.css, src/css/layout/sites.css
=> Fix inline overflow on sites with long links

src/css/config/sites.css, src/index.html
A poorly named website done with React :trollface:.
Closes #91.
=> Add website W3 ARIA-AT
